--- #YAML:1.0
name:               Class-XSAccessor
version:            0.08
abstract:           Generate fast XS accessors without runtime compilation
author:
    - Steffen Mueller <smueller@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    AutoXS::Header:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
